var x = 4, y = '4'

var sacha = {
    nombre: 'Sacha'
}

var otraPersona = {
    nombre: 'Sacha'
}

//IGUALACIONES 
//EL TRIPLE IGUAL SE DEBE USAR SIEMPRE QUE SE PUEDE PORQUE SI HACES EL DOBLE ESTE CASTEA LOS DATOS
//CUANDO INSTANCIAS UN OBJETO RESTRUCTURADO (DESGLOSADO) -> ES OTRO ESPACIO DE MEMORIA